# Generated by Django 5.1.6 on 2025-05-04 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=25)),
                ('vehicle_short_title', models.CharField(max_length=255, null=True)),
                ('vehicle_image', models.ImageField(upload_to='vehicle_image')),
                ('vehicle_product_short_desc', models.CharField(max_length=255, null=True)),
                ('vehicle_product_desc', models.TextField(default=None, null=True)),
                ('vehicle_motor_type', models.CharField(max_length=255, null=True)),
                ('vehicle_range', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_top_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_motor_power', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_horsepower', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_torque', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_feature_1', models.TextField()),
                ('vehicle_feature_2', models.TextField()),
                ('vehicle_feature_3', models.TextField()),
                ('vehicle_feature_4', models.TextField()),
                ('vehicle_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
