# Generated by Django 5.1.6 on 2025-03-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='banner',
        ),
        migrations.DeleteModel(
            name='BannerSection',
        ),
    ]
